# Generated by Django 2.2.3 on 2019-07-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('den', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Den',
        ),
    ]
